# This is a basic workflow that is manually triggered

name: Run Cron

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: "15 8,17 * * *"
    # - cron: '30 5 * * 2,4'

env:
  APP_VAR: ${{ vars.APP_VAR }}
  APP_DEMO: ${{ secrets.APP_DEMO }}
  BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
  BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}

permissions: # Global permissions configuration starts here
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  post1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # - run: |
       # FOO="${{ github.event.inputs.foo }}"
       # echo "FOO=${FOO}" >> $GITHUB_ENV

      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Run a script
        run: |
          pwd
          echo "${{ github.ref }}"
          echo "${{ github.repository }}"
          echo "${{ github.event_name }}"
          ls ${{ github.workspace }}
          chmod +x ./test.sh
          stat ./test.sh
          ./test.sh
          which php
          php ./cron.php
          # touch README.md
          echo "-- last run $(date +%Y%m%d_%H%M%S)"  >> ./README.md
        shell: bash
        
      - name: Commit files
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "updating the repo automatically"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
