name: Run Cron

on:
  workflow_dispatch:
  # push:
  schedule:
    # - cron: "15 8,17 * * *"
    # - cron: '30 5 * * 2,4'

env:
  BLUESKY_USERNAME: ${{ vars.BLUESKY_USERNAME }}
  BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}

permissions: # Global permissions configuration starts here
  contents: write

jobs:
  bluesky:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
     # - run: |
       # FOO="${{ github.event.inputs.foo }}"
       # echo "FOO=${FOO}" >> $GITHUB_ENV

      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Run a script
        run: |
          pwd
          echo "${{ github.ref }}"
          echo "${{ github.repository }}"
          echo "${{ github.event_name }}"
          ls ${{ github.workspace }}
          chmod +x ./test.sh
          stat ./test.sh
          ./test.sh
          which php
          php ./cron.php
          # echo "-- last run $(date +%Y%m%d_%H%M%S)"  >> ./README.md
        shell: bash
        
      - name: Commit files
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "updating the repo log"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          
      - run: echo "This job's status is ${{ job.status }}."
